In [1]:
import numpy as np
import pandas as pd

def getNormed(this_array, this_min = 0, this_max = 255, set_to_int = True):
    new_var = this_array.copy()
    print(new_var)
    print(new_var.max() - new_var.min())
    rat = (this_max - this_min)/(new_var.max() - new_var.min())
    print(rat)
    new_var = new_var * rat
    print(new_var)
    print(new_var.min())
    new_var -= new_var.min()
    new_var += this_min
    if set_to_int:
        return new_var.astype('uint8')
    return new_var

arr1 = np.array([1203, -1025, 87, 0, 1870, 288, 99, -990, 248])
getNormed(arr1)

[ 1203 -1025    87     0  1870   288    99  -990   248]
2895
0.08808290155440414
[105.96373057 -90.28497409   7.66321244   0.         164.71502591
  25.36787565   8.72020725 -87.20207254  21.84455959]
-90.28497409326424


array([196,   0,  97,  90, 255, 115,  99,   3, 112], dtype=uint8)

In [2]:
arr = np.array([1203, 87, 288, 99, 1200, 248])

In [3]:
arr.max()

1203

In [4]:
arr.min()

87

In [5]:
getNormed(arr)

[1203   87  288   99 1200  248]
1116
0.22849462365591397
[274.87903226  19.87903226  65.80645161  22.62096774 274.19354839
  56.66666667]
19.879032258064516


array([255,   0,  45,   2, 254,  36], dtype=uint8)